# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages

    docker:
      - image: cypress/base:8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - ~/.cache
          key: v2-dependencies-{{ checksum "package.json" }}

      # lint!
      - run: yarn lint

      # run tests!
      - run: yarn test

      # Boot up the server for integration tests
      - run:
          command: yarn start
          background: true

      # Run the integration tests once the server is available
      - run:
          command: yarn run wait-on http://localhost:6060 && yarn cypress run
          environment:
            CYPRESS_VIDEO: 'true'
            CYPRESS_VIDEO_UPLOAD_ON_PASSES: 'false'
            CYPRESS_VIDEOS_FOLDER: /tmp/artifacts

      # Capture any videos saved by the integration tests
      - store_artifacts:
          path: /tmp/artifacts
